# Generated by Django 4.0.4 on 2024-04-17 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('show_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='do_list',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='do_list',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
