# Generated by Django 4.0.4 on 2024-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_list', '0002_do_list_deadline_alter_do_list_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
