# Generated by Django 4.0.4 on 2024-04-17 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_list', '0003_alter_do_list_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_list',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
